name: User service CI/CD

on:
  push:
    branches: [main, feature/microservices-migration]
    paths:
      - ECommerce/src/Services/User/**
      - .github/workflows/user-service.yml
      - .github/workflows/_service-ci-cd.yml
  pull_request:
    paths:
      - ECommerce/src/Services/User/**
      - .github/workflows/user-service.yml
      - .github/workflows/_service-ci-cd.yml
  workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/_service-ci-cd.yml
    with:
      service-name: user
      api-project: ECommerce/src/Services/User/ECommerce.User.Api/ECommerce.User.Api.csproj
      docker-context: ./ECommerce/src/Services/User
      dockerfile: ./ECommerce/src/Services/User/Dockerfile
      image-name: ghcr.io/vaibhavjainibm/ecommerce-user-service
      deployment-name: ecommerce-user-service
      container-name: user-api
    secrets: inherit
